export const listaCompetencias: string[] = [
    "Java",
    "Angula",
    "Python",
    "C#",
    "Django",
    "Ruby",
    "GO",
    "JavaScript",
    "PostgreSQL",
    "TypeScript",
    "Rust",
    "Swift",
    "Kotlin",
    "Scala",
    "PHP",
] 